site_name: HFT Book
copyright: Copyright &copy; 2022 <b>Lucas RODRIGUEZ</b>. All rights reserved<br>Other trademarks are the property of their respective owners.
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.sections
    - toc.follow
    - navigation.instant
    - header.autohide
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
# Extra features
extra:
  generator: false

repo_url: https://github.com/hftbook/
repo_name: Official Git repo

# Extensions
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      title: On this page
      permalink: true
      permalink_title: Anchor link to this section for reference

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Navigation center
nav:
  - Home: index.md
  - About: about.md
  - Software: software/index.md
  - Statistics:
      - Home: statistics/index.md
      - Overview of heavy-tailed distribution: statistics/heavy-tails.md
  - Hardware:
      - Home: hardware/index.md
      - FPGA: hardware/fpga.md
  - Network:
      - Home: hardware/network/index.md
      - Direct Market Access: hardware/network/dma.md
  - Data: data/index.md
  - References: bibliography.md
  - TODO: todo.md
